on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    # environment: release  # Optional: for enhanced security
    environment: staging
    permissions:
      id-token: write     # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - run: pnpm install
      - run: pnpm install turbo --global
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
        with:
          url: https://staging.crates.io
      - run: pnpm run publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
